name: Badges

on: push

jobs:
  generate-badges-on-badges-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: |
          cd app
          npm install    

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Tests
        run: |
          cd app
          npm run test:coverage

      - name: Build with Maven
        run: |
          mvn clean test jacoco:report -f api/pom.xml
          mv api/target/ target/

      - name: Check if badges branch exists
        run: |
          branch_name="badges"
          if ! git ls-remote --exit-code origin refs/heads/$branch_name; then
            echo "Branch $branch_name does not exist. Creating it..."
            git checkout -b $branch_name
            git rm -rf *
            git push -u origin $branch_name
            git checkout main
          else
            echo "Branch $branch_name already exists."
          fi

      - name: Switch to badges branch
        run: git switch badges

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          coverage-summary-path: app/coverage/coverage-summary.json
          no-commit: true
          target-branch: badges

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          coverage-label: junit coverage
          badges-directory: badges
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'FeimeiChen'
            git config --global user.email 'FeimeiChen@users.noreply.github.com'
            git add .
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/