name: Generate badges

on: push

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'FeimeiChen'
          git config --global user.email 'FeimeiChen@users.noreply.github.com'

      - name: Create the badges branch if it doesn't exist
        run: |
          branch_name="badges"
          if ! git ls-remote --exit-code origin refs/heads/$branch_name; then
            echo "Branch $branch_name does not exist. Creating it..."
            git checkout --orphan $branch_name
            git rm -rf .github
            git rm -rf .
            git commit --allow-empty -m "Initial commit for $branch_name"
            git push -u origin $branch_name
          else
            echo "Branch $branch_name already exists."
          fi
  generate-jacoco-badges-on-badges-branch:
    needs: create-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v2
        with:
          ref: badges
          path: badges

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven and Generate JaCoCo Report
        run: |
          mvn clean test jacoco:report -f api/pom.xml -D'logging.level.edu.hawaii.its.holiday=OFF' -D'logging.level.org.springframework=ERROR' -D'spring.main.banner-mode=off'
          mv api/target/ target/    

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          coverage-label: junit coverage
          badges-directory: badges
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'FeimeiChen'
            git config --global user.email 'FeimeiChen@users.noreply.github.com'
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badge" *.svg
            git push origin badges -f 
          fi

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

  generate-jest-badges-on-badges-branch:
    needs: create-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v2
        with:
          ref: badges
          path: badges


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: |
          cd app
          npm install

      - name: Tests
        run: |
          cd app
          npm run test:coverage 
          
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          coverage-summary-path: app/coverage/coverage-summary.json
          no-commit: true
          target-branch: badges

      - name: Commit and push badges
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'FeimeiChen'
            git config --global user.email 'FeimeiChen@users.noreply.github.com'
            git add *.svg
            git commit -m "Autogenerated Jest badges" *.svg
            git push origin badges -f
          fi    
