name: Generate badges

on: push

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'FeimeiChen'
          git config --global user.email 'FeimeiChen@users.noreply.github.com'

      - name: Create the badges branch if it doesn't exist
        run: |
          branch_name="badges"
          if ! git ls-remote --exit-code origin refs/heads/$branch_name; then
            echo "Branch $branch_name does not exist. Creating it..."
            git checkout --orphan $branch_name
            git rm -rf .github
            git rm -rf .
            git commit --allow-empty -m "Initial commit for $branch_name"
            git push -u origin $branch_name
          else
            echo "Branch $branch_name already exists."
          fi

  generate-jest-badges-on-badges-branch:
    needs: create-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: |
          cd app
          npm install

      - name: Tests
        run: |
          cd app
          npm run test:coverage 

      - name: Switch to badges branch
        run: git switch badges

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          coverage-summary-path: app/coverage/coverage-summary.json
          no-commit: true
          target-branch: badges

      - name: Commit and push badges
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'FeimeiChen'
            git config --global user.email 'FeimeiChen@users.noreply.github.com'
            git add .
            git commit -m "Autogenerated Jest badges"
            git push origin badges -f
          fi    
