name: Coverage

on: push

jobs:
  generate-badges-on-badges-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if branch exists and create if not
        run: |
          exists=$(git show-ref refs/heads/badges)
           if [ -n "$exists" ]; then
              echo "Branch badges already exists."
          else
              git checkout -b badges
              echo "Branch badges created."
          fi 
          shell: bash

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: |
          cd app
          npm install

      - name: Build with Maven
        run: |
          mvn clean test jacoco:report -f api/pom.xml
          mv api/target/ target/

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          coverage-label: junit coverage
          badges-directory: badges
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Tests
        run: |
          cd app
          npm run test:coverage

      - name: Switch to badges branch
        run: git switch badges

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          coverage-summary-path: app/coverage/coverage-summary.json
          no-commit: true
          target-branch: badges


      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'FeimeiChen'
            git config --global user.email 'FeimeiChen@users.noreply.github.com'
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badge and Jest badges" *.svg
            git push
          fi

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
